system('echo "Fetching npm dependencies..."; npm install')

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
install! 'cocoapods', :disable_input_output_paths => true

target 'NowYouSeeReact-Demo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'NowYouSeeReactTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Flipkart"
  end
  
  pod 'NowYouSeeReact', :path => '../../'
  pod 'NowYouSeeMe'
  pod 'FCChatHeads', :modular_headers => true
  pod 'SwiftLint'
  pod 'GDPerformanceView-Swift'
  pod 'React-Core', :path => '../node_modules/react-native/', :modular_headers => true
end
